config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, inverse_of: :comments
  belongs_to :parent, optional: true, class_name: 'Comment', inverse_of: :comments

  has_many :comments, foreign_key: :parent_id, dependent: :destroy, inverse_of: :parent
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, inverse_of: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :set_parent, only: %i[show new create]

  def index
    @comments = @post.comments.where(parent_id: nil)
  end

  def show; end

  def new
    @comment = Comment.new
  end

  def edit; end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.parent = @parent
    @comment.save
  end

  def update
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  private

  def set_post
    @post = Post.find_by(id: params[:post_id])
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def set_parent
    @parent = Comment.find_by(id: params[:parent_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <p><%= comment.content %></p>

  <div style="display: flex; flex-direction: row">
    <%= link_to "Edit", edit_comment_path(comment, post_id: post.id) %> |
    <%= button_to "Destroy", comment, method: :delete %> |
    <%= link_to "Reply", new_comment_path(parent_id: comment.id, post_id: post.id), data: { turbo_frame: dom_id(comment, :new_comment) } %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <%= hidden_field_tag :post_id, post.id %>
  <%= hidden_field_tag :parent_id, local_assigns[:parent]&.id %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>

    <% target = local_assigns[:parent] || comment %>
    <% if target&.persisted? %>
      <%= link_to "Cancel", comment_path(target, post_id: post.id) %>
    <% end %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend dom_id(@parent || @post, :comments) do %>
  <%= turbo_frame_tag dom_id(@comment, :wrapper), src: comment_path(@comment, post_id: @post.id, parent_id: @parent&.id) %>
<% end %>

<%= turbo_stream.replace dom_id(@parent || @post, :new_comment) do %>
  <% if @parent %>
    <%= turbo_frame_tag dom_id(@parent, :new_comment) %>
  <% else %>
    <%= turbo_frame_tag dom_id(@post, :new_comment), src: new_comment_path(post_id: @post.id) %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment, :wrapper) %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "form", comment: @comment, post: @post %>
<% end %>

app/views/comments/index.html.erb
<%= turbo_frame_tag dom_id(@post, :comments) do %>
  <% @comments.each do |comment| %>
    <%= turbo_frame_tag dom_id(comment, :wrapper), src: comment_path(comment, post_id: @post.id) %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag dom_id(@parent || @post, :new_comment) do %>
  <%= render "form", comment: @comment, post: @post, parent: @parent %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag dom_id(@comment, :wrapper) do %>
  <div style="<%= 'padding-left: 2px; border-left: 2px solid grey;' if @parent %>">
    <%= render @comment, parent: @parent, post: @post %>

    <%= turbo_frame_tag dom_id(@comment, :new_comment) %>

    <%= turbo_frame_tag dom_id(@comment, :comments) do %>
      <% @comment.comments.each do |comment| %>
        <%= turbo_frame_tag dom_id(comment, :wrapper), src: comment_path(comment, post_id: @post.id, parent_id: @comment.id) %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace @comment do %>
  <%= turbo_frame_tag @comment, src: comment_path(@comment, post_id: @post.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedComments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<h3>Comments</h3>
<%= turbo_frame_tag dom_id(@post, :new_comment), src: new_comment_path(post_id: @post.id) %>
<%= turbo_frame_tag dom_id(@post, :comments), src: comments_path(post_id: @post.id) %>